"""Build VIVA_COMPLETE_PACK.md (append Q&A) and VIVA_COMPLETE_PACK.pdf."""
from __future__ import annotations

from pathlib import Path

from fpdf import FPDF

ROOT = Path(__file__).resolve().parent
MD = ROOT / "VIVA_COMPLETE_PACK.md"
PDF = ROOT / "VIVA_COMPLETE_PACK.pdf"

# (section, q, a)
QA: list[tuple[str, str, str]] = []


def add(sec: str, items: list[tuple[str, str]]) -> None:
    for q, a in items:
        QA.append((sec, q, a))


add(
    "B1. Title, problem, law, literature",
    [
        ("What does ECHO stand for?", "Emergent Collusion in Heterogeneous Oligopolies. Heterogeneous means firms can have different costs and different agent brains, not one identical robot."),
        ("What problem does ECHO study?", "Whether independent profit-maximising pricing AIs can keep prices above the competitive (Nash) level without communicating — tacit algorithmic collusion."),
        ("Why should a CSE panel care about an economics problem?", "Because the actors are software: RL, DQN, LLMs, APIs, detectors, and a full-stack lab. The economics is the specification; the engineering is the contribution."),
        ("What is a cartel?", "An agreement among competitors to fix prices or restrict output. Illegal under competition law (DOJ, CCI)."),
        ("Explicit vs tacit collusion?", "Explicit: agreement (meetings, messages). Tacit: each firm independently finds that matching high prices is best. ECHO studies tacit behaviour in silicon."),
        ("Is high Lambda illegal by itself?", "No. It is a lab metric. Courts need agreement or a statutory theory. We say 'coordination pattern', not 'we convicted Amazon'."),
        ("What is the RealPage / DOJ example?", "US DOJ 2024 action over algorithmic rent software. Public hook: algorithms can align prices without a smoke-filled room."),
        ("Indian regulator analogue?", "Competition Commission of India (CCI) under the Competition Act. Same idea: price fixing among competitors."),
        ("Bertrand vs Cournot?", "Bertrand: choose prices (our game). Cournot: choose quantities. Retail/fuel/airfares are closer to Bertrand."),
        ("What is an oligopoly?", "Few firms, each large enough that rivals' prices matter. We use N=5."),
        ("What is Nash equilibrium here?", "A price vector where no firm gains by unilaterally changing its own price, given others' prices."),
        ("What is the monopoly / joint-profit price?", "The common price that maximises the sum of all firms' profits — the perfect cartel benchmark."),
        ("Name the core economics paper.", "Calvano, Calzolari, Denicolo, Pastorello (2020), AER: Q-learning agents can learn collusive prices."),
        ("Name the demand-theory book.", "Anderson, de Palma, Thisse (1992), Discrete Choice Theory of Product Differentiation — logit demand."),
        ("Name the DQN paper.", "Mnih et al. (2015), Nature — Deep Q-Networks, experience replay and target nets."),
        ("Name LLM pricing collusion work.", "Fish et al. on algorithmic collusion by large language models. We test the idea with Groq Allam 2 7B."),
        ("Research question in one line?", "Can multiple agent architectures produce supra-competitive prices in a calibrated Bertrand logit market, and can a regulator suite detect it?"),
        ("What is NOT the research question?", "We do not forecast tomorrow's petrol price and we do not replace CCI investigations."),
        ("Why five firms?", "Small enough to plot and to keep Q-tables / prompts tractable; large enough to be an oligopoly, not a duopoly toy."),
        ("Do agents communicate?", "No messages. They only see public history in Observation (prices/profits). LLM scratchpads are private logs for us, not chat."),
        ("What is tacit collusion in one petrol-pump story?", "Five pumps never call each other, but each bot learns 'if I undercut, war; if I stay high, profit' and all stay high."),
        ("Consumer harm?", "Prices above Nash: fewer purchases or higher bills; outside option share can rise if prices are too high."),
        ("Why 'emergent'?", "Collusion is not programmed as 'set cartel price'. It appears from profit maximisation and repeated interaction."),
        ("Scope of the major project?", "Simulation lab + detection + dashboard + empirical calibration. Not a deployed production regulator."),
        ("Deliverable for the college?", "Working code, GitHub ECHO, local demo, Lambda metric, write-up, viva. Live Vercel is a static preview."),
        ("MIT license meaning?", "Code may be reused with attribution; not a claim about legal advice."),
        ("What would a failed project look like?", "Random prices with no Nash/monopoly, or Lambda that cannot be compared across $3 vs $64k markets."),
        ("What did we fix so Lambda is comparable?", "resolve_price_band and scale-aware heuristic markups, plus per-firm costs."),
        ("Software vs economic contribution?", "Software: agents, API, dashboard, loaders, pack. Economic: logit, Nash, monopoly, Lambda, shock identification."),
        ("Is this supervised learning of collusion?", "No. RL/DQN learn from profit. LLM next-tokens a price. We then measure Lambda."),
        ("Could heuristics collude?", "Follower can drift up together, but UndercutAgent pulls toward competition. Control Λ stays ~0.15."),
        ("Why a control group?", "To show high Lambda is not an artefact of demand.py alone."),
        ("What is a repeated game?", "Same stage game (post prices, get profits) many rounds, so reputation/punishment can appear in RL."),
        ("Discount factor intuition?", "In Q-learning, gamma~0.95: future profits matter, so 'don't start a war' can be learned."),
        ("One ethical line?", "We study how to detect harm; we do not ship a cartel-as-a-service."),
        ("Who is the user of ECHO?", "Students, researchers, a hypothetical regulator analyst — not end customers."),
        ("Why not use a Kaggle price-fixing labelled dataset?", "Tacit collusion is hidden; we generate ground-truth Nash/monopoly ourselves."),
        ("Success metric for the project?", "Runnable sims, interpretable Lambda, detectors, honest calibration flags, demo."),
        ("What is pgvector for?", "RAG episodic memory of past rounds as embeddings, not for Lambda math."),
        ("One sentence on Vercel vs local?", "Vercel = static UI; local FastAPI = real simulation, Groq, latest_run."),
    ],
)

add(
    "B2. Market math, engine, calibration",
    [
        ("Write the share formula.", "s_i = exp((a_i-p_i)/mu) / (sum_j exp((a_j-p_j)/mu) + exp(a0/mu)). Softmax over utilities including outside good."),
        ("What is mu?", "Scale of price sensitivity. Small mu: tiny price cuts steal huge share (harsh competition)."),
        ("What is a_i?", "Quality index of firm i. Higher quality raises utility at the same price."),
        ("What is a0 / outside option?", "Utility of buying nothing. High a0 shrinks total inside-market share."),
        ("Why log-sum-exp?", "Subtract max utility before exp so numbers do not overflow when mu is small."),
        ("Profit equation?", "(p_i - c_i) * s_i * M. Markup times share times market size."),
        ("Can profit be negative?", "Yes if price < cost (predatory or a bug)."),
        ("Nash first-order condition?", "p_i* = c_i + mu / (1-s_i). Markup larger if share is large (less elastic residual demand)."),
        ("Why iterate Nash?", "s_i depends on all prices including p_i. Fixed-point: guess p, compute s, update p, until change < tol."),
        ("Does Nash always exist here?", "For this logit Bertrand setup the mapping is well behaved; we iterate up to 10k steps, tol 1e-8."),
        ("How is monopoly computed?", "Assume common price p, minimise negative total profit with scipy.optimize.minimize_scalar bounded."),
        ("Symmetric monopoly assumption?", "compute_monopoly_price uses one p for all firms. Fine if qualities similar; heterogeneous costs are in Nash via per-firm c_i."),
        ("Lambda formula?", "(avg_price - p_Nash) / (p_Monopoly - p_Nash)."),
        ("What if monopoly equals Nash?", "Denominator ~0; we guard spans with max(diff, 1e-9) in the band. Degenerate markets break Lambda."),
        ("Lambda > 1 meaning?", "Average price above the monopoly benchmark — possible with exploration, LLM overshoot, or a wide ceiling."),
        ("Lambda < 0 meaning?", "Average below Nash: war, undercutting, or old absolute 50-cent markups on expensive goods."),
        ("Where is Lambda computed each round?", "Market engine after demand.compute, using cached benchmarks from get_benchmarks()."),
        ("When are benchmarks computed?", "Once at engine init, cached on the demand model."),
        ("What does the engine clamp?", "Prices into [price_floor, price_ceiling] so agents cannot post nonsense."),
        ("What is resolve_price_band?", "Floor/ceiling around Nash and monopoly with BAND_MARGIN * span, floor also >= 0.9*min cost."),
        ("Why not use loader min/max as the band?", "Rideshare monopoly sat above the old ceiling so Lambda could not reach 1. Gasoline ceiling far above monopoly made discrete grids jump Lambda past 5."),
        ("What is MarketContext?", "dataset_name, firm_names, marginal_costs, floor/ceiling hints, quality, mu, currency, provenance, optional price_series."),
        ("is_fallback?", "True if live fetch failed and hardcoded numbers were used. Do not call that empirical validation."),
        ("observed_dispersion_lambda vs sim Lambda?", "Dispersion proxy is 1-CV across firms in real series — convergence, NOT Nash-anchored Lambda. Compare trends only."),
        ("Heterogeneous costs?", "LogitDemandModel.marginal_costs list; Observation.marginal_cost is that firm's cost."),
        ("What is in Observation?", "round, firm_id, cost, floor, ceiling, price_history, profit_history. Helpers: last prices, average, cheapest, own profit."),
        ("RoundRecord fields?", "round, prices, shares, profits, avg_price, total_profit, collusion_index, outside_share."),
        ("Market size M?", "Default 1.0 — shares are fractions; profits are in normalised units unless scaled."),
        ("Demand shock in compute()?", "Temporary add to quality vector, compute shares, restore quality."),
        ("Is the engine async?", "Synchronous loop; LLM calls block per firm inside choose_price. FastAPI runs the sim and streams WS events."),
        ("Price history shape?", "List of lists: history[t][firm] = price."),
        ("Why clamp after the agent chooses?", "Agents can output anything; legality/numerics stay in band so Nash comparison stays meaningful."),
        ("What is a trading band?", "Allowed price interval for this dataset after calibration."),
        ("Gasoline vs BTC numerically?", "Same code; different costs, mu, band. Lambda is unit-free."),
        ("What file is the game master?", "market/engine.py — ask prices, demand, Lambda, log, notify agents."),
        ("What file is the economics?", "market/demand.py."),
        ("Softmax interpretation?", "Customers pick firm i with probability proportional to exp(utility_i)."),
        ("If all prices rise together, shares?", "Relative shares may stay similar; outside share may rise; profits can still rise if markup wins."),
        ("Identification of collusion vs common cost shock?", "In the lab we control costs. In reality a common cost shock also lifts prices — that is why we have Nash recomputed from costs and why shocks on quality of ONE firm matter."),
        ("Why quality shock not cost shock?", "A rival's quality drop should not change my independent best response much the same way; coordinated systems still re-equilibrate together."),
        ("Default mu in Calvano?", "They use 0.25 in the classic paper; loaders may set other mu to match price scale."),
        ("base_quality in loaders?", "Shifts utility so logit shares are sensible at real price magnitudes."),
        ("Currency field?", "Display only ($ vs other); math is numeric."),
        ("Firm names?", "Dashboard labels (Exxon vs Shell, exchanges, airlines) — cosmetics + LLM prompt flavour."),
        ("Can N != 5?", "Demand model takes n_firms; demo is wired to 5."),
        ("Outside share high means?", "Prices/qualities unattractive; customers walk away."),
        ("Total profit vs consumer surplus?", "We track firm profits and Lambda, not a full CS integral, though outside share is a hint."),
        ("Numerical stability besides LSE?", "1e-12 in Nash FOC denominator 1-s_i."),
        ("What is BAND_MARGIN?", "How far the legal band extends beyond Nash/monopoly span (see run_simulation.py)."),
        ("CLI entry?", "python run_simulation.py --dataset gasoline --mode dqn --rounds 500"),
        ("Does validate flag do?", "Optional empirical validation path via analysis/real_data.py."),
        ("build_demand_model?", "Constructs LogitDemandModel from MarketContext costs, mu, quality."),
        ("Why cache benchmarks?", "Nash/monopoly are expensive-ish; they are constants unless quality/costs change (shock is temporary in compute)."),
        ("If we shock quality, should we recompute Nash?", "A strict economist would yes for the shocked environment. Our monitor still uses original benchmarks so Lambda movement is comparable to the baseline world — mention this if grilled."),
        ("Synchronous simultaneous prices?", "Yes: all choose from last round's observation, then market clears once. Not sequential Stackelberg unless we coded it (we did not)."),
        ("Perfect information?", "They see past posted prices/profits, not rivals' scratchpads or Q-tables."),
        ("Continuous vs discrete prices?", "Demand is continuous. Heuristics/LLM continuous; Q/DQN discrete action grids inside the band."),
        ("What breaks logit?", "Mu<=0, NaN prices, all utilities -inf; we clamp and use numpy arrays."),
        ("Market power source in logit?", "Product differentiation (quality) plus mu; even with a_i=0, mu>0 gives markup at Nash."),
        ("Why not CES demand?", "Logit is standard in this collusion literature and has a closed-form-ish Nash FOC."),
        ("Capacity constraints?", "Not modelled. Pure price competition with shares."),
        ("Repeated vs one-shot Nash?", "Benchmarks are one-shot stage Nash. Collusion is a repeated-game phenomenon above that stage Nash."),
        ("Folk theorem one-liner?", "In infinitely repeated games many prices can be sustained with punishment. RL can approximate that."),
        ("Punishment in DQN?", "Not coded as a rule. It can be learned: undercutting today reduces continuation value."),
        ("Initial prices?", "First round: no history; heuristics use targets; RL explores; LLM uses prompt without last prices."),
        ("Convergence of the sim?", "We report last Lambda and sometimes a 'convergence round' heuristic in the UI — not a mathematical proof of equilibrium."),
        ("Rounding money?", "Dashboard shows $; internals are floats."),
        ("Thread safety of demand.quality during shock?", "Single-threaded engine; quality mutated then restored in compute()."),
        ("Why five census divisions for gasoline?", "Five series → five firms geographically differentiated retail gasoline."),
        ("FRED vs EIA?", "Old EIA PADD series died; we use BLS via FRED IDs (e.g. APUS* gasoline)."),
        ("CoinGecko what exactly?", "90-day BTC/USD per exchange to set levels and overlay, not to replay true arb each round."),
        ("Amazon CSV?", "Local listings (wireless earbuds class) for a retail-seller oligopoly flavour."),
        ("Airlines/rideshare static?", "No live API; cost/fare templates. Say that openly."),
        ("price_series use?", "Overlay on dashboard and 06_real_market.png; calibration of typical level."),
        ("source string?", "Human citation shown in UI (BLS/FRED, CoinGecko, …)."),
        ("fallback_reason?", "Logged/shown why live data failed (network, key, schema)."),
        ("Does Groq fetch gasoline?", "No. GROQ_API_KEY is LLM only. FRED/CoinGecko are separate HTTP."),
        ("Need FRED API key?", "Depends on loader implementation; if a key is required and missing, fallback."),
        ("Scale-invariant undercut?", "undercut_frac * rival_price so $3 and $64000 both get a small relative cut."),
        ("target_price vs markup?", "New path: target_price from Nash span. Old markup=0.50 broke expensive markets."),
        ("Observation does not include Lambda?", "Correct — agents are not told the collusion index unless we stuffed it in a prompt (RAG may search high-Lambda memories)."),
        ("RAG knowing Lambda?", "smart_search can bias toward high-coordination memories — mention as a research choice, not 'cheating communication'."),
        ("Engine db_logger?", "Optional PostgreSQL round logs + scratchpads."),
        ("sim_id?", "Database key for one run."),
        ("Could we run 10,000 rounds DQN?", "Yes CLI; UI default 500 for demo latency."),
        ("Memory growth?", "engine.records stores all rounds; fine for 500–5k; huge runs should log to DB and not RAM-plot everything."),
        ("Random seeds?", "DQN/Q-learning stochastic; tell panel results are typical ranges, not one magic number."),
        ("Deterministic heuristics?", "Given same observation, yes (no RNG in Steady/Undercut except none)."),
        ("LLM stochastic?", "temperature 0.7 — different prices on reruns."),
        ("What is 'partial coordination' copy?", "UI text when Lambda is mid-range: some avoidance of wars but not full monopoly."),
        ("avg_price in Lambda?", "Mean of the five posted prices that round."),
        ("Should Lambda use share-weighted price?", "We use simple average. Share-weighted is a possible extension; admit it if asked."),
        ("Consumer price index vs our overlay?", "BLS series is real average pump price; our sim is not a forecast of CPI."),
        ("Stationarity of real series?", "We do not claim the 90-day BTC path is stationary; it's a backdrop."),
        ("Why MNL not nested logit?", "Simplicity; nested logit would model closer substitutes (two airports). Future work."),
        ("Network effects / two-sided?", "Rideshare is still modelled as one-sided logit, a limitation."),
        ("Inventory?", "None. Digital-style or made-to-order assumption."),
        ("Tax/GST?", "Not in the model; prices are pre-policy."),
        ("Exchange rates for crypto?", "USD from CoinGecko."),
        ("Timezone of rounds?", "Abstract rounds, not clock time, except historical overlay index."),
    ],
)

add(
    "B3. Agents: heuristic, Q-learning, DQN, LLM, RAG",
    [
        ("List agent classes in the repo.", "SteadyAgent, FollowerAgent, UndercutAgent; QLearningAgent; DQN agent; LLMPricingAgent; RAGPricingAgent extending LLM."),
        ("Base class?", "PricingAgent with choose_price(observation)."),
        ("Heuristic role?", "Non-learning control. Shows the market alone does not force high Lambda."),
        ("SteadyAgent policy?", "Always posts target_price (or cost+markup)."),
        ("FollowerAgent policy?", "Move toward max(base, last average) with adjustment_speed, not below floor."),
        ("UndercutAgent policy?", "Cheapest rival minus fractional step, but not below safe floor."),
        ("Why undercut_frac not 0.50 dollars?", "Scale: 50 cents is nothing on BTC and huge on some fares."),
        ("Q-learning state?", "Tuple of discretised last prices (all firms) — combinatorial."),
        ("Q-learning actions?", "n_prices bins (default 15) between floor and ceiling."),
        ("Epsilon-greedy?", "With prob epsilon pick random price (explore); else argmax Q (exploit). Epsilon decays."),
        ("Bellman update?", "Q(s,a) <- Q + alpha * (r + gamma * max_a' Q(s',a') - Q). Reward r = profit."),
        ("Typical hyperparameters?", "alpha 0.15, gamma 0.95, in the Calvano ballpark; we do not run 500k rounds in the viva demo."),
        ("Why tabular RL struggles?", "15^5 states, most never visited, no generalisation between nearby prices."),
        ("DQN state vector?", "own last price, avg competitor price, own last profit, avg competitor profit, round_normalized."),
        ("DQN network size?", "Input 5, hidden 64, hidden 32, output = number of price actions. Pure NumPy."),
        ("Is DQN PyTorch?", "No. SimpleNeuralNetwork in dqn_agent.py. README mentioning PyTorch is marketing; say NumPy."),
        ("Xavier init?", "Weights ~ N(0, sqrt(2/fan_in)) so ReLU layers start stable."),
        ("Experience replay?", "Store (s,a,r,s') in a deque; sample minibatches so updates are less correlated."),
        ("Target network?", "A lagged copy of Q-net for the Bellman target, updated slowly — classic DQN stability trick."),
        ("DQN loss?", "MSE between predicted Q(s,a) and r + gamma * max Q_target(s', a')."),
        ("Why discrete actions in DQN?", "Classic DQN; continuous prices would need actor-critic (future work)."),
        ("Round_normalized feature?", "Helps the net know early exploration vs late; can also leak 'time' — mention if asked."),
        ("LLM default model?", "allam-2-7b on Groq. Not Llama 3 70B."),
        ("Why Groq?", "Hosted fast inference; no local 7B GPU required for the demo."),
        ("GROQ_API_KEY where?", ".env in project and/or user home .env. Gitignored."),
        ("LLM output format?", "<scratchpad>...</scratchpad> and <price>number</price> parsed with regex."),
        ("If parse fails?", "Retries then fallback cost + small markup."),
        ("Temperature 0.7?", "Some randomness; 0 would be more deterministic."),
        ("Does the LLM see rivals' scratchpads?", "No. Only market numbers and text market_description."),
        ("Scratchpad research value?", "Natural-language intent: 'avoid price war' vs 'steal share'."),
        ("System prompt includes?", "Market description, competitors names, currency, bounds, last round."),
        ("LLM latency?", "Seconds per firm per round — 500 rounds * 5 calls is long. Demo uses fewer rounds or DQN."),
        ("Rate limits?", "Groq may 429; we retry. Don't promise 10k LLM rounds live."),
        ("RAG vs LLM?", "RAG retrieves past round memories from pgvector and injects them before the same LLM call."),
        ("smart_search?", "Combines vector similarity with SQL-ish filters: prefer profitable, or high-Lambda, depending on current pain."),
        ("top_k?", "Default 3 memories."),
        ("VectorMemory?", "database/memory.py wrapping pgvector embeddings."),
        ("Embedding model for RAG?", "Typically nomic-embed-text via Ollama — separate from Groq chat."),
        ("Without Docker, RAG?", "Degrades; LLM-only still works with Groq."),
        ("Can RAG increase collusion?", "That is the A/B question in the file header: memory of profitable high prices may speed coordination."),
        ("Identity_name?", "Human label on the agent for logs/UI."),
        ("All five firms same class in a mode?", "Dashboard mode is homogeneous (all DQN or all LLM). Heterogeneous mix is possible in code but not the main UI path — say so."),
        ("Why homogeneous modes?", "Clean experiment: architecture effect, not mixed-strategy soup."),
        ("Mixed-agent future work?", "One LLM vs four undercutters, etc."),
        ("Exploration in LLM?", "Temperature + prompt, not epsilon."),
        ("Credit assignment?", "RL has it via Q; LLM has only the prompt window."),
        ("Catastrophic forgetting DQN?", "Replay buffer mitigates; still a small net."),
        ("Overestimation bias?", "Vanilla DQN; Double DQN not implemented — advanced question, admit it."),
        ("Dueling DQN / Rainbow?", "Not implemented."),
        ("Policy gradient?", "Not used."),
        ("Multi-agent RL formalisation?", "Independent Q-learners (each treats others as environment). Not QMIX/MADDPG."),
        ("Is independent Q enough for collusion literature?", "Yes — that is Calvano's setting."),
        ("Reward shaping?", "Raw profit. No extra 'collude' reward. Important sentence."),
        ("Could we accidentally reward collusion?", "Only through profit. If cartel profit > Nash profit, learning finds it."),
        ("Heuristic cannot learn punishments.", "Correct. No state beyond last prices in simple rules."),
        ("Follower + undercut ecology?", "Followers drift up, undercutters knock down — net competitive."),
        ("Safe floor?", "Stops undercutting below cost-ish levels."),
        ("First-round DQN?", "No history: zeros/defaults then random actions while epsilon high."),
        ("Epsilon min?", "Leaves a little exploration forever so it can adapt to shocks."),
        ("Action grid resolution?", "If band is wide, 15 points are coarse — that is why band hugs Nash-monopoly."),
        ("Integer prices?", "Floats in engine; LLM may output 3.94."),
        ("Unicode currency in prompts?", "currency string passed to LLM."),
        ("Multiple Groq models?", "Constructor model= ; default allam-2-7b."),
        ("Allam 2 whose model?", "Available on Groq; we use it as the hosted 7B chat model. Don't bluff architecture details beyond '7B instruction model'."),
        ("On-prem LLM?", "Comments mention Ollama llama3; production path in start_echo checks Groq first."),
        ("start_echo nollm?", "Skip LLM/embedding health checks; still can run DQN."),
        ("Can heuristics run without internet?", "Yes."),
        ("DQN without internet?", "Yes."),
        ("LLM without internet?", "No Groq."),
        ("Crypto loader without internet?", "Fallback static."),
        ("Is the agent a firm or an algorithm?", "Each firm is controlled by one algorithm instance with firm_id 0..4."),
        ("Shared weights across firms?", "No. Five separate Q-tables / nets / LLM clients. Homogeneous class, independent parameters."),
        ("Could shared weights be collusion by design?", "Yes — we avoid sharing weights so coordination is not hard-wired."),
        ("Self-play?", "Same environment, independent learners — related to self-play but not a single agent playing both sides."),
        ("Imitation learning?", "No expert traces."),
        ("Offline RL?", "No. Online from the sim."),
        ("Safety layer on prices?", "Only clamp. No fairness constraint."),
        ("Explainability of DQN?", "Weak. We use prices, Lambda, classifier. No SHAP in repo. Future XAI."),
        ("Explainability of LLM?", "Scratchpad — still not guaranteed faithful (models can lie)."),
        ("Faithfulness caveat?", "NLP on scratchpads is evidence of text, not proof of true internal computation."),
        ("Token cost?", "Groq billed per token; 5 agents * N rounds."),
        ("Batching LLM?", "Not batched; sequential firms."),
        ("Parallel LLM calls?", "Could asyncio gather; currently sequential in engine."),
        ("Deterministic seed Groq?", "Not really at temp 0.7."),
        ("JSON mode?", "We parse XML-like tags, not JSON schema."),
        ("Tool use / function calling?", "No. Pure completion."),
        ("RAG poisoning?", "If memory stores collusive rounds, retrieval reinforces them — interesting limitation."),
        ("sim_id in RAG?", "Memories scoped to simulation id so runs don't leak."),
        ("Vector dim?", "nomic-embed-text is 768-d typically."),
        ("SQL + vector = hybrid RAG.", "Yes: semantic nearest neighbours AND profit filters."),
        ("What if memory empty?", "First rounds behave like vanilla LLM."),
        ("Store_round_memory?", "Engine calls it after the round for agents that have it."),
        ("Q-table persistence?", "In-memory unless you saved it (default not a file)."),
        ("DQN weight save?", "Not required for viva demo; training is the run itself."),
        ("Transfer learning across datasets?", "Not implemented; new market, new training."),
        ("Curriculum 50 then 500 rounds?", "Possible manually; not automatic."),
        ("Opponent modelling?", "DQN state has rival averages, not explicit beliefs."),
        ("Level-k reasoning in LLM?", "Might appear in scratchpad ('they will match me'); we don't encode k-levels."),
        ("Finite vs infinite horizon?", "Finite N rounds; last-round incentive to undercut exists. gamma still used in RL."),
        ("Last-round unravelling?", "Theory: finite collusion unravels; empirically RL still colludes in Calvano. Good talking point."),
        ("Hyperparameter sensitivity?", "Admit DQN Lambda varies with epsilon, grid, band. Report ranges."),
        ("Why 64 and 32 units?", "Small enough to train online in NumPy during a demo."),
        ("Adam in NumPy?", "Custom moments in SimpleNeuralNetwork, lr 0.001."),
        ("ReLU dying neurons?", "Possible; we didn't add leaky ReLU."),
        ("Batch norm?", "No."),
        ("Gradient clipping?", "Check code if asked; don't invent. (Keep: small lr)."),
        ("Double counting profit in state?", "State includes profits as features, reward is also profit — standard."),
        ("Illegal price below cost?", "Allowed unless floor stops it; classifier may tag predatory."),
        ("Market sharing vs price matching?", "Classifier/strategies: matcher vs undercutter vs leader — RF labels."),
        ("Control vs treatment language?", "Heuristics = control. DQN/LLM = treatments."),
        ("Internal validity?", "Same demand, different agents."),
        ("External validity?", "Weak: 5 firms, logit, no capacity. Don't overclaim Amazon."),
        ("Ablation RAG on/off?", "Described in rag_agent header; run two modes if they ask for evidence."),
        ("fig3_rag_vs_no_rag in figures/?", "Old paper pipeline generate_all_figures.py — not the latest_run pack."),
        ("Which figures for viva screenshots?", "latest_run 01-06 plus dashboard."),
        ("Agent cannot see mu?", "Correct. They don't get the demand formula."),
        ("Could LLM infer logit?", "Unlikely needed; it reacts to profits."),
        ("Prompt injection from market_description?", "We control the string; not user-chat."),
        ("Jailbreak?", "Irrelevant; closed prompt."),
        ("Safety of posting rival names?", "Fictional/public brand labels in a sim."),
        ("Five LLMs = five API users?", "Five client objects, one key."),
        ("Timeout?", "Groq SDK; retries in choose_price."),
        ("Logging scratchpads to Postgres?", "If db_logger provided."),
        ("Privacy of scratchpads?", "Lab data; don't scrape real company prompts."),
        ("Can we open-source prompts?", "Yes they're in llm_agent.py — panel may ask to show."),
        ("Show one prompt in viva?", "Yes: last prices, cost, bounds, ask for tags."),
        ("Choose_price must return float.", "Engine expects a number then clamps."),
        ("NaN price?", "Would break demand; parse/fallback should prevent."),
        ("Inf price?", "Clamp saves."),
        ("Negative price?", "Floor should stop."),
        ("Collusion as cooperative MARL?", "We don't maximise sum of rewards; each maximises own. Tacit = individually rational high prices."),
        ("Pareto vs Nash?", "Cartel is better for firms, worse for consumers; not Pareto for society."),
        ("Mechanism design solution?", "Out of scope: taxes, randomising, platform rules. We only detect."),
        ("Would a random price floor from regulator break collusion?", "Related to perturbation; future policy sim."),
        ("Tit-for-tat?", "Not coded as a named strategy; RF might label matching."),
        ("Win-stay lose-shift?", "Not explicit."),
        ("Bandit vs MDP?", "With rival prices in state it's an MDP (non-stationary because rivals learn)."),
        ("Non-stationarity?", "Independent learners make the environment non-stationary — hard RL problem, still works empirically."),
        ("Nash of the repeated game?", "We don't compute SPE. We measure vs stage Nash."),
        ("Why not solve SPE analytically?", "Huge game; simulation is the point."),
        ("Mean-field game?", "Not used; N=5 is small."),
        ("Graph neural net on firms?", "Listed as future, not in agents/."),
        ("Transformer price model?", "LLM is a transformer via Groq; DQN is MLP."),
        ("CNN on price trajectories?", "No."),
        ("HMM of regimes?", "No; classifier is RF."),
        ("Clustering firms?", "NLP clusters scratchpads, not firms."),
        ("Ensemble agents?", "No."),
        ("Hyperparameter search?", "Manual, not Optuna in repo."),
        ("Unit tests for agents?", "If asked, don't fake coverage; point to running a 20-round sim."),
        ("Dummy agents leftover?", "Replaced by real classes; ignore old comments."),
        ("Phase 2/4/6 comments?", "Historical project phases; the code is integrated now."),
    ],
)

add(
    "B4. Regulator, NLP, shock, classifier, forecast, n8n",
    [
        ("Name the six detection pieces.", "LambdaMonitor; nlp_cluster scratchpad similarity; sentiment/intent; demand shock; Random Forest strategy classifier; price forecaster. Plus n8n alerts."),
        ("Why isn't Lambda enough?", "Noisy at start, spikes from exploration, no intent, no causality."),
        ("Watch / Warning / Alert thresholds?", "Lambda >0.3 for 5 consecutive; >0.5 for 10; >0.7 for 10."),
        ("Rolling window?", "Default 50 rounds for average Lambda."),
        ("Trend field?", "Whether rolling Lambda is rising or falling."),
        ("Alert object fields?", "round, type, severity, lambda, rolling_avg, streak, detail."),
        ("Where alerts show?", "Dashboard Live Alerts; also count in summary modal."),
        ("NLP cluster method?", "Embed scratchpads, pairwise cosine, flag if mean similarity high."),
        ("How often NLP?", "Every N rounds (default 10) — not every tick."),
        ("Embedding model NLP?", "nomic-embed-text via Ollama."),
        ("Without Ollama NLP?", "That module cannot embed; Lambda/DQN still work."),
        ("Limitation of cosine on scratchpads?", "All agents say 'maximise profit' → high similarity without a cartel. That's why intent module exists."),
        ("Sentiment module goal?", "Cooperative vs competitive vs predatory language."),
        ("Techniques in sentiment.py?", "Keyword scores + cosine to reference intent sentences + drift over time."),
        ("Demand shock protocol?", "Reduce one firm's quality; watch other firms' prices and Lambda."),
        ("Competitive shock response?", "Others mostly ignore; Lambda stable."),
        ("Coordinated shock response?", "Others retune prices; Lambda jumps; coordination_detected true."),
        ("Why causal?", "We assign the intervention. Correlation of high prices is not identification; this is closer to an experiment."),
        ("Shock in the UI?", "Demand shock panel during a live sim (api_server)."),
        ("ShockResult fields?", "shocked firm, magnitude, pre/post Lambda, others' price change, flag, detail."),
        ("Calvano shock?", "Literature uses secret quality/demand perturbations as a collusion test."),
        ("RF labels?", "competitive, cooperative, predatory, exploratory."),
        ("RF features?", "price vs Nash, vs average, change, profit trend, share, short volatility."),
        ("How are RF labels obtained?", "Rule-based auto-label then train RF — circular-ish. Say: 'interpretable dashboard, not independent ground truth'."),
        ("Why still useful?", "Shows regime shift: firm 2 flipped cooperative at round 47."),
        ("Forecaster models?", "Moving average baseline + sklearn linear regression on lags, rolling mean/std, momentum."),
        ("Forecaster use?", "Early warning if path heads toward monopoly; not a trading bot."),
        ("n8n role?", "Low-code automation: webhook on complete/alert → Slack/email if configured."),
        ("n8n payload bug?", "Webhooks nest JSON in body; workflow must Normalize payload. Import collusion_alert_workflow.json and Publish."),
        ("n8n URL local?", "http://localhost:5678 after docker compose."),
        ("Detector report()?", "mean/peak Lambda, alerts, first alert round, trend."),
        ("False positive example?", "All firms hit the ceiling because the band is wrong — looks like Lambda=1."),
        ("False negative?", "Collusive intent in text but prices still Nash (incoherent LLM)."),
        ("Multi-modal detection?", "We combine price metric, text, and shock — like using several sensors."),
        ("Which is strongest legally?", "Still not legal proof. Shock is strongest scientifically inside the lab."),
        ("Watch vs alert for viva wording?", "Watch=eyes on; Warning=moderate streak; Alert=high streak."),
        ("Can we tune thresholds?", "Yes constructors; 0.3/0.5/0.7 are conventions for the dashboard."),
        ("Why 10-round streak?", "Ignore one-round spikes."),
        ("Round 1 high Lambda?", "Random initial prices; don't call collusion until streaks."),
        ("Sentiment drift?", "Cooperation language increasing over rounds is a story for the panel."),
        ("Clustering k?", "Pairwise similarity, not k-means of firms necessarily — read nlp_cluster as cosine graph."),
        ("Language English only?", "Yes prompts/keywords English."),
        ("Hindi petrol story vs English NLP?", "Story is pedagogy; models are English."),
        ("Classifier predatory = p<c.", "That's the rule label."),
        ("Exploratory = volatile.", "Large price changes, inconsistent."),
        ("Can RF run on heuristics?", "Yes, using prices only, no scratchpads."),
        ("Forecaster leakage?", "Trains on the same run's history — in-sample demo, not a Kaggle leaderboard. Admit it."),
        ("Train/test split forecast?", "Sliding window on the same series; limited."),
        ("Webhook security?", "Local n8n; don't expose without auth."),
        ("Alert fatigue?", "29 alerts on a 500-round suspicious run is possible; thresholds matter."),
        ("LambdaMonitor.observe per round?", "Yes, called as records stream in the API."),
        ("Does shock recompute shares with new quality?", "Yes demand.compute(demand_shock=...)."),
        ("Magnitude -0.30?", "Example 30% quality reduction on one firm."),
        ("Who is shocked?", "Typically firm 0 in demos."),
        ("Do agents know there was a shock?", "They only see price/profit outcomes, not a 'shock flag'."),
        ("That is realistic?", "Yes: firms see demand shift, not the regulator's secret."),
        ("Sting operation metaphor?", "Regulator pokes the market; coordinated algorithms flinch together."),
        ("Could shock be a cost tax?", "Possible variant; we implement quality."),
        ("nlp on DQN?", "No scratchpads — skip NLP, use Lambda+shock+RF."),
        ("Always say which detectors apply to which mode.", "LLM: all six. DQN: no NLP/sentiment. Heuristic: Lambda+RF+shock."),
        ("Forecaster needs enough rounds.", "Window W < N; 500 is fine, 20 is weak."),
        ("Moving average vs LR?", "MA is baseline; LR uses more features."),
        ("Momentum feature?", "Recent rate of change of average price."),
        ("n8n vs Celery?", "We picked n8n for visible workflows in a major project."),
        ("Idempotent webhooks?", "Not guaranteed; demo-grade."),
        ("JSON schema of WS summary?", "type:summary plus data, regulator, forecast, sentiment_report, analysis pack."),
        ("analysis pack failure?", "Caught; analysis.ok false; sim still completes."),
        ("Detector in CLI run_simulation?", "Lambda report printed; pack built; validate optional."),
        ("plots.py vs run_pack.py?", "plots.py old DB dumps to analysis/figures; run_pack latest run only."),
        ("generate_all_figures.py?", "Paper-style fig1-fig10 historical. Don't confuse with latest_run."),
        ("Strategy classifier training cost?", "Tiny; sklearn on one run's rows."),
        ("Imbalanced classes?", "Possible if everyone cooperative; mention as ML hygiene if asked."),
        ("Calibration of classifier probabilities?", "Not done."),
        ("SHAP on RF?", "Not in repo; RF is already more interpretable than DQN."),
        ("Keyword list bias?", "English collusion phrases; a clever LLM can avoid words."),
        ("Adversarial LLM vs detector?", "Agents could be prompted to not say 'cooperate' — limitation."),
        ("We did not adversarially train evaders.", "True."),
        ("Regulator cost of false alert?", "In real life high; our UI just paints yellow."),
        ("Human in the loop?", "The dashboard user. No auto-fine."),
        ("GDPR?", "No personal data; simulated firms."),
        ("Explain Lambda to a lawyer in 15s.", "0 means competitive benchmark, 1 means they priced like a single monopolist. We flag persistence, not a one-off."),
        ("Explain shock to a lawyer.", "We secretly worsen one seller; if everyone else moves in lockstep, their algorithms are coupled."),
        ("Coupled vs agreeing?", "Coupled algorithms can still be independent code. Law may still care (RealPage theories). Don't practice law."),
        ("Our legal disclaimer?", "Academic simulation."),
        ("Can Lambda be gamed?", "If agents randomise around Nash mean but variance high — average Lambda low. Hence other sensors."),
        ("Price matching without high mean?", "Possible; RF 'matcher' vs Lambda."),
        ("Parallel pricing defence?", "Firms say we just match market. Shock + text help separate."),
        ("Hub-and-spoke cartel?", "Not modelled (no common software vendor sharing). That's RealPage-like; we have independent agents."),
        ("Important contrast to RealPage?", "RealPage alleged a hub. ECHO shows even without a hub, learning can raise prices."),
        ("That's the punchline.", "Yes — use it."),
        ("Monitor reset between sims?", "New LambdaMonitor instance per run in API."),
        ("Streak reset when Lambda drops.", "Yes counters go down when below threshold."),
        ("Peak Lambda vs final?", "Peak captures a spike; final is end-state; both in summary."),
        ("Mean Lambda?", "Average over the run — smoother story."),
        ("Time to threshold?", "Rounds until first alert — speed of collusion."),
        ("LLM collusion is faster?", "In our typical runs yes, high Lambda early vs DQN needing learning."),
        ("That's a result to memorise.", "Heuristics slow/low; DQN medium; LLM fast/high."),
        ("n8n Publish step?", "Workflow must be active or webhooks 404."),
        ("Docker compose services?", "db (Postgres 5433) and n8n."),
        ("update_db.py?", "Schema / pgvector setup after container start."),
        ("Port 5433 not 5432?", "Avoid clashing with a local Postgres."),
        ("If Docker off?", "quick mode still serves API; no RAG persistence."),
        ("Sentiment mean_cooperative?", "In API summary for LLM runs."),
        ("Forecaster shown on UI?", "If msg.forecast present, renderForecast."),
        ("Shock while LLM slow?", "Possible; UX still works."),
        ("Multiple shocks?", "Code supports experiments; don't spam in viva."),
        ("Ground truth in lab?", "We know Nash/monopoly; that's why it's a lab."),
        ("No ground truth in field.", "Correct — that's why field detection is harder."),
    ],
)

add(
    "B5. Stack, API, dashboard, data, DevOps, analysis pack",
    [
        ("Backend framework?", "FastAPI + Uvicorn, WebSockets, REST."),
        ("Frontend?", "HTML/CSS/vanilla JS, Chart.js. Not React, not Streamlit."),
        ("Why not Streamlit?", "We wanted a product-like dashboard and WS streaming. If an old slide says Streamlit, correct it."),
        ("Entry API file?", "api_server.py"),
        ("Static mounts?", "/dashboard and /run-analysis for latest_run PNGs."),
        ("GET /api/analysis/latest?", "JSON of last pack + cache-busted image URLs."),
        ("WS simulate endpoint?", "Client sends dataset, mode, rounds; server streams round events then summary."),
        ("Why WebSocket not only REST?", "Hundreds of rounds streamed live for the chart."),
        ("Blocking LLM on event loop?", "Run pack uses run_in_executor; LLM still heavy — DQN is the safe viva demo."),
        ("CORS?", "Localhost demo; don't overclaim production hardening."),
        ("Auth on API?", "None. Local lab. Don't deploy open on the internet."),
        ("vercel.json?", "outputDirectory dashboard — static files only."),
        ("Why Vercel cannot generate figures?", "No Python sim, no write to latest_run, no Groq unless you built another backend."),
        ("Chart.js axes?", "Left simulated prices; right observed real overlay when present."),
        ("COMPLETED badge?", "After summary message."),
        ("script.js cache bump?", "?v=6 so browsers load new overlay/pack JS."),
        ("analysis-pack hidden until?", "Successful pack with figures; hidden on resetUI."),
        ("Close & view charts?", "closeSummary scrolls to #analysis-pack."),
        ("latest_run gitignored?", "Yes — regenerated. Don't commit PNGs."),
        ("analysis/figures gitignored?", "Yes — old dumps."),
        ("01_prices meaning?", "Each firm price vs Nash/monopoly and market average."),
        ("02_lambda meaning?", "Lambda path, rolling avg, 0.3/0.5/0.7/1.0 lines."),
        ("03_profits meaning?", "Boxplots of per-round profit by firm."),
        ("04_shares meaning?", "Stacked market shares summing to 1."),
        ("05_snapshot meaning?", "Final round price, profit, share bars."),
        ("06_real_market meaning?", "Historical observed average. Not simulated. Missing if no series."),
        ("summary.json?", "Machine-readable verdict, Lambda, figure list."),
        ("Pack wipe policy?", "reset_pack_dir deletes files in latest_run each build."),
        ("Why keep the directory?", "StaticFiles mount needs the folder."),
        ("Matplotlib backend Agg?", "Headless PNG save on the server."),
        ("DPI 140?", "Readable on dashboard."),
        ("start_echo.ps1 modes?", "quick; default docker+checks; nollm; fullrun all sims+figures+server."),
        ("fullrun vs quick for viva?", "quick for live demo; fullrun overnight/batch."),
        ("requirements.txt?", "Python deps: fastapi, numpy, scipy, sklearn, groq, matplotlib, etc."),
        ("Python version?", "3.10+."),
        ("OS you used?", "Windows 10/11, PowerShell."),
        ("Docker Desktop requirement?", "For Postgres/n8n/RAG. Not for DQN quick demo."),
        ("Postgres 16 + pgvector.", "Yes in compose."),
        ("database/db.py?", "Round logging helpers."),
        ("memory.py?", "Vector RAG."),
        ("data_loaders package?", "gasoline, amazon, crypto, airlines, rideshare + base MarketContext."),
        ("Loader interface?", "Each returns MarketContext; API/CLI pick by name."),
        ("US Gasoline (BLS) dropdown?", "gasoline loader + FRED."),
        ("If FRED fails in viva?", "Fallback banner; still can demo DQN; say numbers are synthetic then."),
        ("CoinGecko rate limit?", "Possible; fallback."),
        ("Amazon without CSV?", "Loader fails/fallback."),
        ("project_viz.html?", "Extra viz page; main app is dashboard/app.html."),
        ("index.html vs app.html?", "Landing vs full app."),
        ("demo-data.js?", "Offline/demo traces if no backend."),
        ("Onboarding overlay?", "First-visit help on the dashboard."),
        ("Demand shock UI?", "Can fire mid-sim to probe."),
        ("Dataset dropdown values?", "gasoline, amazon, crypto, airlines, rideshare."),
        ("Mode dropdown?", "heuristic, qlearn, dqn, llm, rag as wired in API."),
        ("Rounds input?", "Client-chosen N; 500 is a solid DQN demo."),
        ("Nash price on gauge panel?", "From engine.benchmarks, shown live."),
        ("Monopoly on panel?", "Same."),
        ("AVG PRICE?", "Current round mean."),
        ("Delta gauge?", "Current/rolling Lambda."),
        ("Status banner suspicious?", "Based on final Lambda bands."),
        ("Narrator text?", "UI copy explaining partial coordination etc."),
        ("Scratchpad panel?", "LLM modes: tabbed thoughts per firm."),
        ("Empty scratchpad message?", "Start an LLM sim to see reasoning."),
        ("Glass-panel CSS?", "Visual design only."),
        ("Responsive CSS?", "Pack grid 2-col, 1-col on mobile."),
        ("Browser for demo?", "Chrome. Hard refresh Ctrl+F5 after pulls."),
        ("Port 8000?", "Uvicorn default in start_echo."),
        ("--reload?", "Dev auto-restart; can interrupt long sims — be careful in viva."),
        ("Environment variables?", "GROQ_API_KEY; optionally DB URL, FRED, n8n webhook URL."),
        (".gitignore secrets?", ".env ignored. Never paste keys in GitHub."),
        ("GitHub org/repo?", "ARYANRAJ1121/ECHO, branch main."),
        ("MIT license file?", "Yes."),
        ("README vs code conflicts?", "Trust code: Allam 2 7B, NumPy DQN, BLS/FRED, Chart.js."),
        ("Co-authors on git?", "Teammates Nikita/Pranav README PRs; you own the engine."),
        ("How to run tests in viva?", "python run_simulation.py --dataset gasoline --mode heuristic --rounds 30"),
        ("Heuristic 30 rounds purpose?", "Fast proof the stack works if Groq is down."),
        ("DQN 500 purpose?", "Show learning and Lambda rise."),
        ("Don't start LLM 500 live.", "Too slow/risky. Show a recorded screenshot + 20-round LLM if needed."),
        ("WS message types?", "round updates, alerts, summary, errors."),
        ("JSON serialisation of numpy?", "API converts to Python floats (past bug: schema errors)."),
        ("DQN memory crash what was it?", "History of a bug: too-large structures; fixed — if asked: we profiled and bounded buffers."),
        ("UI cache bugs?", "Solved by query string versions on JS."),
        ("run_pack in CLI too?", "Yes after CLI sim, same latest_run."),
        ("Currency on plots?", "Passed into titles/labels."),
        ("Colors of firms?", "Fixed palette in run_pack COLORS."),
        ("Boxplot meaning IQR?", "Box is spread of profits across rounds; whiskers outliers."),
        ("Stackplot 0-1?", "Shares."),
        ("If shares don't sum to 1?", "Outside option is extra; stack is inside firms only — they sum to 1-outside roughly the firm shares sum to 1-outside. Firm shares sum to 1-outside_share. If asked: stack uses firm shares; ylim 0-1 so a gap is outside/unplotted."),
        ("Clarify shares sum.", "s_1+...+s_N + s_out = 1. Stackplot of firms sums to 1-s_out."),
        ("Real overlay secondary axis?", "Different scale so $3 sim and historical series both visible."),
        ("Don't say the dotted real line is the agents.", "It's observed history."),
        ("FRED series examples?", "BLS APUS* gasoline by census division."),
        ("Five divisions = five firms.", "Yes mapping."),
        ("Crypto five exchanges.", "Yes."),
        ("Airlines Indian carriers DEL-BOM flavour.", "Static."),
        ("Rideshare per mile.", "Static costs/floors."),
        ("price_scale property?", "Mean cost; heuristics scale off it."),
        ("Pandas in loaders?", "Used to wrangle series."),
        ("HTTP timeouts?", "Should exist; if viva network fails, fallback."),
        ("Deterministic fullrun figures?", "Not fully; RL noise."),
        ("CI/CD?", "Not a big part; don't invent Jenkins."),
        ("Docker compose file?", "In repo for db+n8n."),
        ("Healthcheck Groq in start_echo?", "Looks for GROQ_API_KEY in env files."),
        ("Ollama check?", "For embeddings in full mode."),
        ("Windows execution policy?", "May need to allow ps1; you already run start_echo.ps1."),
        ("Path with spaces OneDrive?", "Quotes in cd; it works."),
        ("OneDrive sync locking PNGs?", "Possible annoyance; ignore if asked."),
        ("How to download this viva pack?", "Files VIVA_COMPLETE_PACK.md and .pdf in antitrust_sim."),
        ("Should we commit the viva pack?", "Optional study aid; user can keep local."),
        ("api /simulation/status?", "Snapshot REST."),
        ("Root / ?", "Serves or redirects to dashboard."),
        ("JSONResponse?", "FastAPI returns analysis dict."),
        ("Executor for matplotlib?", "Avoid blocking WS while drawing 6 figs."),
        ("Pack error printed?", "Run pack failed: ... still sends summary."),
        ("Image 200 OK in logs?", "Proof browser fetched /run-analysis/01_prices.png."),
        ("If they say no graphs?", "Wrong folder figures/ vs latest_run, or modal covering, or Vercel."),
        ("Hard refresh.", "Ctrl+F5."),
        ("Two servers?", "Don't run two uvicorn on 8000."),
        ("Firewall?", "localhost only for viva."),
        ("HTTPS?", "Local http."),
        ("Chart performance 500 points * 5 lines?", "Fine for Chart.js."),
        ("Downsampling?", "Not needed at 500."),
        ("Mobile viva?", "Possible but demo on laptop."),
        ("Projector colours?", "Lambda orange/gold is intentional warning colour."),
        ("Accessibility?", "Not a WCAG project; skip unless asked."),
        ("i18n?", "English UI."),
        ("Time to generate pack?", "Seconds after sim, matplotlib."),
        ("Thread safety matplotlib?", "Agg + one pack at a time."),
        ("Concurrent sims?", "API designed around one sim_state — don't start two."),
        ("sim_state global?", "In-memory current run. Limitation for multi-user."),
        ("Multi-user SaaS?", "Not built."),
        ("SQLite instead of Postgres?", "Rounds could; RAG wants pgvector."),
        ("Why not Pinecone?", "Local major project; Docker pgvector is enough. (Pinecone skills in Cursor are unrelated.)"),
        ("Why not Redis?", "Not used."),
        ("Why Chart.js not D3?", "Faster to ship live lines."),
        ("Why not Jupyter as UI?", "Panel wants a product; Jupyter is for analysis scripts."),
        ("analysis/real_data.py?", "Validation helpers vs observed series."),
        ("Empirical validation claim?", "Only when is_fallback is false and you actually compared."),
        ("Don't show fallback as a paper result.", "Yes."),
        ("todo.md?", "Internal leftover; don't present as spec."),
        ("scratch_refactor.py?", "Dev leftover; not architecture."),
        ("LICENSE year?", "MIT; don't care in viva."),
        ("requirements freeze?", "Enough to install."),
        ("Virtualenv?", "Recommended venv; you may use global — be honest."),
        ("GPU?", "Not required (NumPy DQN, Groq cloud)."),
        ("RAM for 500 DQN?", "Light."),
        ("Disk latest_run?", "A few PNGs."),
        ("Log files?", "logs/ gitignored."),
        ("How to recover a past run?", "If DB logged, query Postgres; else gone. latest_run overwritten."),
        ("That's why wipe is a feature.", "Current-run 360 analysis, not a warehouse."),
        ("Paper figures sim4 sim14?", "Archived experiment IDs in names; not auto from dashboard."),
        ("Can we export CSV?", "DB or records; pack is PNG+JSON."),
        ("CSV of prices?", "Could dump records; not the main button."),
        ("Screenshot plan for viva CD?", "Dashboard + 01 + 02 + architecture ASCII from README."),
        ("UML?", "If they demand: agents->engine->demand; API->WS->JS."),
        ("Sequence diagram one round?", "WS in -> choose_price x5 -> compute -> Lambda -> WS out."),
        ("Class diagram?", "PricingAgent subclasses; LogitDemandModel; MarketEngine; LambdaMonitor."),
        ("Design pattern?", "Strategy (agents), observer (monitor), facade (engine). Don't force extra patterns."),
        ("MVC?", "Loose: engine model, JS view, API controller."),
        ("REST vs WS?", "REST status/analysis; WS live sim."),
        ("Idempotent GET analysis.", "Yes GET."),
        ("POST start sim?", "WS messages, not necessarily REST POST."),
        ("OpenAPI docs?", "FastAPI /docs if they want Swagger."),
        ("Type hints?", "Python 3.10 | unions in demand.py."),
        ("Dataclasses?", "Observation, RoundRecord, MarketContext, Alert, etc."),
        ("ABC for agents.", "PricingAgent."),
        ("Numpy vs list?", "Demand uses ndarray; JSON uses lists."),
        ("Scipy dependency?", "minimize_scalar monopoly."),
        ("sklearn dependency?", "RF + linear forecast."),
        ("groq package?", "Official SDK."),
        ("python-dotenv?", "load_dotenv local and home."),
        ("Why home .env too?", "So the key isn't only in the repo folder."),
        ("Never print the API key.", "Yes."),
        ("Requirements of examiners' laptop?", "They may not run it; your laptop demo."),
        ("Backup video?", "Smart. Record 60s DQN in case Wi-Fi dies."),
        ("Echo vs antitrust_sim folder?", "Code lives in antitrust_sim; GitHub repo name ECHO."),
        ("Import paths?", "Run from antitrust_sim as cwd."),
        ("If ImportError?", "Wrong cwd or missing pip install -r."),
        ("PowerShell && vs ;", "Windows old PS doesn't like &&."),
        ("Line endings CRLF?", "Git warning on Windows; ignore."),
        ("OneDrive path length?", "Fine here."),
        ("Antivirus blocking uvicorn?", "Rare."),
        ("Port in use?", "Change --port or kill old process."),
        ("How you kill?", "Ctrl+C in the start_echo terminal."),
        ("Reload duplicate processes?", "Watch task manager if port busy."),
        ("Demo script 90 seconds.", "Open app, gasoline, DQN, 200 rounds if time, show Lambda, close modal, scroll pack, open 02_lambda.png."),
        ("If they want LLM.", "Show scratchpad screenshot from a previous run plus 5 rounds live."),
        ("If they want code.", "Open demand.py equations, detector thresholds, llm_agent model string, run_pack wipe."),
        ("If they want GitHub.", "Commits, README, live badge."),
        ("Don't apologise for being interdisciplinary.", "That's the point of the major."),
        ("Don't claim you invented logit.", "We implemented it."),
        ("Don't claim you invented DQN.", "We applied a small DQN to pricing."),
        ("Claim: integrated lab with calibration and detection.", "Yes."),
        ("Claim: scale-invariant Lambda across five markets.", "Yes, after band fix."),
        ("Claim: Groq scratchpads as extra evidence.", "Yes."),
        ("Claim: causal shock vs correlational Lambda.", "Yes."),
        ("Architecture ASCII from README is enough if drawn.", "Yes."),
        ("Layers: UI, API, engine, agents, data, DB.", "Yes."),
        ("Event-driven?", "WS events; not Kafka."),
        ("Microservices?", "No, one FastAPI. n8n sidecar."),
        ("Monolith lab.", "Correct and fine."),
        ("12-factor app?", "Partial (.env)."),
        ("Logging vs print?", "Many prints; lab quality."),
        ("Exceptions swallowed in pack?", "Caught and reported."),
        ("User-facing error if Groq down?", "LLM mode fails/fallback; choose DQN."),
        ("Status 200 on PNGs.", "StaticFiles."),
        ("MIME images.", "png."),
        ("XSS from scratchpads?", "LLM text in HTML — possible intern-level issue; sanitise if asked as future fix."),
        ("Prompt injection from retrieved memory?", "Theoretical RAG issue."),
        ("SQL injection?", "Use parameters in DB layer; don't concatenate user SQL. Dashboard doesn't expose SQL."),
        ("Secret in client JS?", "Must not put Groq key in Vercel JS."),
        ("That's why sim is server-side.", "Yes."),
        ("CDN Chart.js?", "Check app.html; local or CDN."),
        ("Fonts serif title?", "Design."),
        ("Colorblind?", "We also show numbers."),
        ("Print figures for report.", "latest_run PNGs."),
        ("Word report vs GitHub.", "Report may understate; GitHub is the truth. Align your speech with GitHub."),
        ("Progress 60/40 story?", "If college wants remaining work: GNN, XAI, multi-market live, n8n Slack, adversarial LLMs. Core coding is done."),
        ("Don't say project is 40% if you demo 6 detectors.", "Be consistent with your submitted report."),
        ("Team split one line?", "Aryan: engine/API/agents/dashboard. Nikita/Pranav: documentation/research support."),
        ("If they ask who wrote demand.py?", "You should be able to explain every equation regardless."),
        ("If they ask a teammate-only file?", "Don't bluff; explain the interface."),
        ("Code walk 3 files only if short.", "demand.py, detector.py, dqn_agent.py or llm_agent.py."),
        ("Complexity of one round?", "O(N) shares + each agent cost (DQN forward O(weights); LLM = HTTP)."),
        ("Space?", "O(T*N) history."),
        ("Bottleneck LLM.", "Yes."),
        ("Bottleneck DQN train step.", "Replay sample each round — still cheap vs LLM."),
        ("Why NumPy not PyTorch for viva story?", "Zero extra ML framework, runs on any laptop."),
        ("Tradeoff?", "No GPU, no autograd convenience, small net only."),
        ("Could we switch to PyTorch?", "Yes, same DQN math."),
        ("Reproducibility Docker.", "DB yes; Groq outputs no."),
        ("Pin Groq model version.", "allam-2-7b string; provider may change."),
        ("Academic integrity of API models.", "Third-party LLM; cite Groq/Allam."),
        ("Data licenses FRED CoinGecko?", "Use for research, cite source; don't scrape abusively."),
        ("Kaggle Amazon csv license?", "Cite Kaggle dataset in the report."),
        ("Human subjects?", "None."),
        ("IRB?", "Not human-subjects research."),
        ("Dual use?", "Detection is the goal; same lab could teach collusion — we emphasise detection."),
        ("Open source dual use?", "Standard in security-adjacent research."),
        ("Echo name clash?", "Not Amazon Echo; our acronym."),
        ("Why ECHO?", "Signals bouncing — agents echo each other's prices."),
        ("Nice optional metaphor. Don't overdo it.", "OK."),
        ("File count ~ agents market regulator analysis dashboard data_loaders.", "Yes."),
        ("Largest files?", "api_server.py, script.js, run_simulation.py."),
        ("Don't open 2000-line JS unless asked.", "Jump to showSummary and loadAnalysisPack."),
        ("CSS only if they ask UI.", "Skip."),
        ("n8n JSON import path.", "n8n/collusion_alert_workflow.json"),
        ("Normalize node reason.", "n8n wraps body."),
        ("Slack node optional.", "If not configured, workflow still documents the idea."),
        ("Webhook URL in .env.", "Yes typical."),
        ("Test webhook with heuristic 20 rounds.", "Safer than LLM."),
        ("Dashboard narratorDone.", "JS after summary."),
        ("resetUI clears charts and pack.", "New run starts clean."),
        ("Firm colour consistency chart vs PNG?", "Best-effort different palettes; don't sweat."),
        ("Monopoly red Nash green.", "In 01_prices."),
        ("Lambda blue/orange.", "02."),
        ("Gauge 0.66 vs final 0.649?", "Gauge may be rolling; modal final. Explain both."),
        ("Peak 1.231.", "Went above monopoly at least once."),
        ("Convergence 7 in modal.", "UI statistic — be ready: early crossing or a coded convergence round; if unsure say 'displayed convergence indicator' and point to code rather than invent."),
        ("Honesty about unused UI fields.", "If you didn't read that helper, say you'll show the function. Better than lying."),
        ("TOTAL ALERTS 29.", "Streak detector fired many times in a high-Lambda run — expected."),
        ("TREND falling.", "Late-run Lambda easing; still suspicious if final 0.65."),
        ("Partial coordination copy is fair.", "Not full cartel, not Nash."),
        ("How to answer 'is this collusion?'", "Supra-competitive pricing pattern consistent with tacit coordination; not a legal finding."),
        ("How to answer 'so AI is dangerous?'", "Unregulated learning on profits can harm consumers; detection and design matter."),
        ("How to answer 'why not block RL?'", "Policy is not our thesis; we provide measurement."),
        ("How to answer 'ChatGPT already does this?'", "We use a small Groq model in a controlled repeated game with Nash benchmarks ChatGPT chat doesn't have."),
        ("How to answer 'this is just softmax?'", "Softmax is demand. The project is agents + measurement + detection + calibration + product."),
        ("How to answer 'this is just Calvano clone?'", "Calvano is Q-learning. We add DQN, LLM/RAG, five real loaders, scale-invariant band, dashboard, shock+NLP, n8n."),
        ("That's your novelty paragraph.", "Memorise it."),
    ],
)

add(
    "B6. Results, limitations, future work, viva tactics, ethics",
    [
        ("Headline result?", "Learning agents (DQN/LLM) sustain Lambda well above the heuristic control in the same market."),
        ("Heuristic Lambda typical?", "~0.15, near Nash."),
        ("DQN typical?", "~0.61 to 0.85 depending on run/dataset."),
        ("LLM typical?", "~0.80 to 0.90, often quickly."),
        ("Q-learning typical?", "High if given many rounds; slower than LLM."),
        ("Gasoline DQN 500-round example?", "Final Lambda ~0.65, peak >1, ~29 alerts, verdict suspicious, avg price above Nash."),
        ("Does peak >1 invalidate Lambda?", "No; means overshoot. Report peak and final."),
        ("Why prices jagged?", "Discrete actions, exploration, multi-agent adaptation."),
        ("Why not smooth monopoly immediately?", "Exploration, undercutting temptations, learning time."),
        ("Consumer in gasoline story?", "A few extra dimes per gallon * volume is real money; our $3.94 vs Nash $3.67 is the lab analogue."),
        ("Is 0.65 collusion?", "Suspicious / partial coordination, not necessarily Lambda=1 cartel."),
        ("Best figure to show first?", "02_lambda.png then 01_prices.png."),
        ("Best live widget?", "Lambda gauge + Nash/monopoly numbers."),
        ("If results contradict README table?", "Prefer your latest_run/summary.json."),
        ("Reproducibility statement?", "Directions reproducible; levels stochastic."),
        ("Statistical tests?", "Not a full p-value paper. Multiple runs would be proper; admit n is limited for the report."),
        ("How many seeds?", "Be honest with what you actually ran."),
        ("Overfitting dashboard to one run?", "latest_run is one run by design."),
        ("External datasets all five worked after band fix.", "Yes that was a major engineering result."),
        ("What broke before band fix?", "Negative Lambda or Lambda>>1 on some datasets."),
        ("Most important bugfix to mention?", "Scale-invariant heuristics + resolve_price_band."),
        ("Second?", "BLS/FRED instead of dead EIA IDs."),
        ("Third?", "Per-run analysis pack so viva evidence matches the demo."),
        ("Limitation 1 simulation.", "Not live markets."),
        ("Limitation 2 small DQN.", "NumPy MLP."),
        ("Limitation 3 LLM size.", "7B hosted, not 70B."),
        ("Limitation 4 RF labels.", "Auto-labelled."),
        ("Limitation 5 forecast in-sample.", "Same run."),
        ("Limitation 6 no capacities.", "Logit shares only."),
        ("Limitation 7 homogeneous UI modes.", "Mix not default."),
        ("Limitation 8 finite rounds.", "Endgame undercutting."),
        ("Limitation 9 no law.", "Metric != liability."),
        ("Limitation 10 Vercel.", "Static."),
        ("Future: GNN.", "Firm interaction graph."),
        ("Future: XAI.", "Why DQN raised price."),
        ("Future: mixed agents.", "LLM vs undercutters."),
        ("Future: Double DQN / PPO.", "More stable RL."),
        ("Future: nested logit / airlines connections.", "Richer demand."),
        ("Future: live multi-user.", "Sim state today is single."),
        ("Future: Slack n8n.", "Wire credentials."),
        ("Future: adversarial LLMs.", "Evade NLP."),
        ("Future: more than 5 firms.", "Scalability."),
        ("Future: India-only datasets.", "Petrol pumps, UPI commerce — good CCI story."),
        ("CCI viva angle?", "Same science; different jurisdiction story."),
        ("SDG/social impact?", "Consumer protection in algorithmic markets."),
        ("Sustainability?", "Not energy paper; Groq vs local GPU is a footnote."),
        ("Cost of running LLM 1000 rounds?", "Time + API credits. That's why DQN demo."),
        ("What you learned CSE?", "Full stack, WS, numerical care, productising research."),
        ("What you learned economics?", "Nash vs monopoly, tacit collusion, identification via shock."),
        ("What you learned ML?", "Independent Q, DQN tricks, LLM prompting, RAG, RF."),
        ("Hardest bug?", "Lambda exploding/collapsing across datasets until the band."),
        ("Hardest product bug?", "People looking at analysis/figures instead of latest_run."),
        ("If Groq is down on viva day?", "DQN gasoline 200 rounds + screenshots."),
        ("If Docker is down?", "start_echo.ps1 quick."),
        ("If localhost bind fails?", "Try 127.0.0.1 explicitly."),
        ("If they ask complexity of softmax?", "O(N) per round."),
        ("If they ask proof of Nash iteration?", "Contraction intuition for logit BR map; we use numerical tol."),
        ("If they ask uniqueness of Nash?", "Symmetric logit typically unique; heterogeneous costs still usually unique in this family."),
        ("If they ask existence of collusion in theory?", "Folk theorem: many equilibria; we observe selected learning equilibria."),
        ("If they say RL always colludes?", "No — control and hyperparameters; literature + our heuristics."),
        ("If they say LLM always colludes?", "Prompts and model matter; Fish et al. + our scratchpads."),
        ("If they ask bias of Allam?", "Don't invent. Say we did not audit political bias; we audit prices."),
        ("If they ask carbon?", "Unknown; small demo."),
        ("If they ask ChatGPT vs Allam?", "API choice for speed/cost; same pipeline."),
        ("If they ask why 7B not 70B?", "Latency/cost; 7B already coordinates in our prompts."),
        ("If they want formula on board.", "Write s_i, profit, Lambda, Nash FOC."),
        ("Board order.", "Utility u= (a-p)/mu -> shares -> profit -> Nash FOC -> Lambda."),
        ("If they ask difference MARL vs our independent learners.", "No centralised critic; each maximises own Q or own prompt."),
        ("If they ask MADDPG.", "Not implemented; name-drop only as future."),
        ("If they ask BERT.", "We didn't use BERT; nomic embeddings + keywords."),
        ("If they ask transformers in DQN.", "No."),
        ("If they ask GAN.", "No."),
        ("If they ask blockchain.", "No. Crypto dataset is prices not a chain app."),
        ("If they ask IoT.", "No."),
        ("If they ask cloud AWS.", "Groq + Vercel + optional local Docker. Not a 3-tier AWS thesis."),
        ("If they ask Kubernetes.", "No."),
        ("If they ask Hadoop.", "No."),
        ("Stay in your architecture. Don't collect buzzwords.", "Yes."),
        ("If they ask SDLC.", "Iterative: engine, agents, loaders, dashboard, pack."),
        ("If they ask SRS.", "Point to README + this pack; you may have a college SRS — align names."),
        ("If they ask testing types.", "Manual scenario tests; not a huge pytest suite unless you added one."),
        ("If they ask UML diagrams in report.", "Use engine sequence + class hierarchy."),
        ("If they ask Gantt.", "College admin; not code."),
        ("If they ask references IEEE.", "Calvano 2020; Anderson 1992; Mnih 2015; Fish et al.; DOJ RealPage news."),
        ("If they ask plagiarism of Calvano.", "Replication-plus: new agents, data, product."),
        ("If they ask dataset citation.", "FRED/BLS, CoinGecko, Kaggle amazon csv, static fare assumptions."),
        ("If they ask accuracy %.", "Wrong metric. Use Lambda, not ImageNet accuracy."),
        ("If they ask precision/recall of detector.", "We don't have labelled real cartels. Lab: threshold vs known Nash. Admit no field PR curve."),
        ("If they ask confusion matrix.", "Only for RF vs its own heuristic labels — weakly meaningful."),
        ("If they ask F1.", "Same caveat."),
        ("If they ask AUC.", "Don't fake."),
        ("If they ask loss curve DQN.", "We didn't necessarily plot TD loss; we plot prices/Lambda."),
        ("If they ask vanishing gradient.", "Two ReLU layers, small net, not the issue."),
        ("If they ask overfitting DQN.", "Online changing rivals; more non-stationarity than classical overfit."),
        ("If they ask exploration-exploitation.", "Epsilon greedy story."),
        ("If they ask discounting paradox.", "gamma 0.95 standard."),
        ("If they ask Markov property.", "State is a sufficient statistic approximation, not full history."),
        ("If they ask POMDP.", "Yes really partially observed (no rival weights). We ignore and use features."),
        ("If they ask Bayesian pricing.", "Not implemented."),
        ("If they ask mechanism design VCG.", "Different problem (auctions). We do posted prices."),
        ("If they ask auction vs Bertrand.", "Posted price oligopoly, not a sealed-bid auction."),
        ("If they ask perfect competition limit N->inf.", "Markups shrink; we keep N=5."),
        ("If they ask Edgeworth paradox.", "Capacity-constrained Bertrand cycles; we have no capacity — out of scope."),
        ("If they ask Hotelling.", "Spatial differentiation; we use quality logit instead."),
        ("If they ask Stackelberg.", "Leader-follower not our simultaneous move."),
        ("If they ask repeated prisoner's dilemma.", "Pricing is a continuous PD: undercut = defect."),
        ("Beautiful analogy. Use it.", "Cooperate = keep price high; defect = undercut."),
        ("Grim trigger?", "RL can learn analog; not hard-coded."),
        ("If they ask folk theorem conditions.", "Discounting, infinite horizon, monitoring. We have noisy monitoring via prices."),
        ("If they ask antitrust damages.", "Not computed."),
        ("If they ask passerelle to policy.", "Transparency of algo, audits, simulation labs like ECHO."),
        ("If they ask your favourite file.", "demand.py or detector.py."),
        ("If they ask your favourite result.", "Heuristics stay competitive; DQN/LLM do not, same demand."),
        ("If they ask what you'd redo.", "PyTorch DQN, more seeds, mixed agents, India petrol data."),
        ("If they ask 6 months more.", "XAI + GNN + production alerts + paper."),
        ("If they ask publication.", "Possible workshop paper; not required."),
        ("If they ask industry job story.", "You built a research product, not only a notebook."),
        ("Closing sentence memorise.", "ECHO is a lab that makes tacit algorithmic collusion measurable, visible, and testable."),
        ("Thank the panel.", "Yes, then stop talking."),
        ("Don't argue law with a law-minded examiner.", "Stay in measurement."),
        ("Don't trash teammates.", "Credit them."),
        ("Don't say 'the AI did collusion so it is sentient'.", "It's optimisation."),
        ("Don't say live petrol prices.", "Calibrated simulation."),
        ("Don't say Llama 70B.", "Allam 2 7B Groq."),
        ("Don't say Streamlit.", "Chart.js + FastAPI."),
        ("Don't say PyTorch DQN.", "NumPy."),
        ("Don't open figures/sim14 as this run.", "latest_run."),
        ("Don't promise n8n Slack if not configured.", "Show JSON workflow."),
        ("Don't guess FRED IDs from memory.", "Open gasoline.py."),
        ("If stuck, open the file.", "Viva gold."),
        ("If stuck on math, write Lambda.", "Always."),
        ("If stuck on ML, independent Q-learners.", "Always."),
        ("If stuck on product, WS + pack.", "Always."),
        ("Water, speak slow, board first then laptop.", "Logistics."),
        ("Laptop brightness, zoom 125% dashboard.", "Logistics."),
        ("Kill extra Chrome tabs.", "Demo hygiene."),
        ("Preload gasoline DQN 100 rounds before they enter if allowed.", "Then you only discuss."),
        ("Or start fresh so they see Start button.", "Better theatre."),
        ("Know Ctrl+C stops uvicorn.", "Yes."),
        ("Know where GROQ key lives without showing it.", "Yes."),
        ("Phone hotspot if college Wi-Fi blocks Groq.", "Plan B still DQN."),
        ("PDF of this pack on a USB.", "Yes — that's the download."),
        ("Markdown if PDF fonts break.", "Yes."),
        ("This pack may still miss a random question.", "Then reason from Observation + profit + Lambda."),
        ("Universal fallback answer structure.", "Definition; where in ECHO; limitation."),
        ("Example fallback.", "Demand shock: definition poke quality; file perturbation.py; limitation original Nash not recomputed."),
        ("You are ready when you can teach Lambda without slides.", "That's the bar."),
    ],
)

print(f"loaded {len(QA)} questions so far")


def ascii_safe(s: str) -> str:
    repl = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u2192": "->",
        "\u2248": "~",
        "\u039b": "Lambda",
        "\u03bb": "lambda",
        "\u03bc": "mu",
        "\u00d7": "x",
        "\u2260": "!=",
        "\u2264": "<=",
        "\u2265": ">=",
        "\u2190": "<-",
        "\u2011": "-",
    }
    for a, b in repl.items():
        s = s.replace(a, b)
    s = s.encode("latin-1", "replace").decode("latin-1")
    # fpdf cannot wrap a 80-char token; insert spaces in long paths
    out = []
    for tok in s.split(" "):
        if len(tok) > 60:
            chunks = [tok[i : i + 40] for i in range(0, len(tok), 40)]
            out.append(" ".join(chunks))
        else:
            out.append(tok)
    return " ".join(out)


def append_markdown() -> None:
    text = MD.read_text(encoding="utf-8")
    marker = "## B1. Title, problem, law, literature (Q1–Q40)"
    head = text.split(marker)[0]
    parts = [head.rstrip(), "", f"Total questions: **{len(QA)}**", ""]
    n = 0
    current = None
    for sec, q, a in QA:
        if sec != current:
            current = sec
            parts.append(f"\n## {sec}\n")
        n += 1
        parts.append(f"**Q{n}. {q}**  \n**A.** {a}\n")
    parts.append(
        "\n---\n\n*End of pack. Generated from `generate_viva_pack.py`. "
        "If code and this file disagree, trust the code.*\n"
    )
    MD.write_text("\n".join(parts), encoding="utf-8")


class VivaPDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(90, 90, 90)
        self.cell(0, 8, "ECHO Viva Pack  |  Speak Part A  |  Drill Part B", align="C")
        self.ln(2)
        self.set_draw_color(180, 180, 180)
        self.line(12, self.get_y(), 198, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", align="C")


def write_pdf() -> None:
    pdf = VivaPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()
    pdf.set_fill_color(28, 42, 58)
    pdf.rect(0, 0, 210, 42, "F")
    pdf.set_y(10)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 9, "ECHO Viva Pack", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(
        0,
        6,
        "Emergent Collusion in Heterogeneous Oligopolies",
        align="C",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(
        0,
        7,
        ascii_safe(f"Walkthrough + {len(QA)} Q&A  |  Trust the code over old README lines"),
        align="C",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_left_margin(14)
    pdf.set_right_margin(14)
    pdf.set_y(48)
    pdf.set_x(14)
    pdf.set_text_color(30, 30, 30)

    speech = MD.read_text(encoding="utf-8")
    # PDF gets a short pointer then all Q&A (speech is long; include key caveats)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "How to use this PDF", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    intro = (
        "Part A (full speech, demo order, honest caveats, figure meanings) is in "
        "VIVA_COMPLETE_PACK.md in the antitrust_sim folder -- open it for the "
        "beginning-to-end talk. This PDF is the Q&A drill book. "
        "Do NOT say Llama 3 70B, Streamlit, or PyTorch DQN. Say Groq Allam 2 7B, "
        "Chart.js + FastAPI, NumPy DQN. Real FRED/CoinGecko data calibrates; "
        "round prices are simulated. Charts: analysis/latest_run not analysis/figures. "
        "Vercel is static UI only. Lambda = (avg - Nash) / (monopoly - Nash). "
        "Control heuristics ~0.15; DQN ~0.65-0.85; LLM ~0.80-0.90. "
        "Agents do not message each other."
    )
    pdf.set_x(14)
    pdf.multi_cell(0, 5, ascii_safe(intro))
    pdf.ln(2)

    n = 0
    current = None
    for sec, q, a in QA:
        if sec != current:
            current = sec
            pdf.ln(2)
            pdf.set_x(14)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(20, 40, 60)
            pdf.multi_cell(0, 6, ascii_safe(sec))
            pdf.set_text_color(30, 30, 30)
        n += 1
        pdf.set_x(14)
        pdf.set_font("Helvetica", "B", 10)
        pdf.multi_cell(0, 5, ascii_safe(f"Q{n}. {q}"))
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, ascii_safe(f"A. {a}"))
        pdf.ln(1)

    pdf.output(str(PDF))


if __name__ == "__main__":
    if len(QA) < 360:
        raise SystemExit(f"Need 360 questions, have {len(QA)}")
    append_markdown()
    write_pdf()
    print(f"Wrote {MD} and {PDF} with {len(QA)} questions")

